#!/usr/bin/env python

from taiga import TaigaAPI
import click

API_HOST = "https://api.taiga.io/"
api = TaigaAPI(host=API_HOST)


@click.group()
@click.option("--username", "-u", prompt=True, help="taiga.io useername or email")
@click.option("--password", "-p", prompt=True, hide_input=True,
              help="taiga.io password")
def cli(username, password):
    """The taiga command interface."""
    api.auth(username=username, password=password)


@cli.command()
@click.option("--project", "-p", "project_slug", prompt=True, help="project slug")
@click.option("--subject", "-s", prompt=True, help="issue subject")
@click.option("--description", "-d", help="issue description")
@click.option("--attachments", "-a", multiple=True, help="issue description")
def add_issue(project_slug, subject, description, attachments):
    """Create a new issue."""
    me = api.me()

    click.echo("  Getting project '{}'...".format(project_slug))
    project = api.projects.list(member=me.id).get(slug=project_slug)

    click.echo("  Creatting issue...'{}'".format(subject))
    description = description or click.edit("...write description here..") or ""
    issue = project.add_issue(subject,
                              project.default_priority,
                              project.default_issue_status,
                              project.default_issue_type,
                              project.default_severity,
                              description=description)

    if attachments:
        with click.progressbar(attachments,
                               label="  Attaching files...") as progressbar:
            for att in progressbar:
                issue.attach(att)


if __name__ == "__main__":
    cli()
